version: '3'

services:
  admin_api:
    build: ./CS-API
    container_name: admin_API
    ports:
      - '8080:8080'
    volumes:
      - ./CS-API:/api

  admin_php:
    build: ./PHP
    container_name: admin_php
    volumes:
      - ./WEB:/usr/local/apache2/htdocs

  admin_web:
    build: ./WEB
    container_name: admin_web
    ports:
      - '8000:80'
    volumes:
      - ./WEB:/usr/local/apache2/htdocs

  admin_db:
    build: ./DB
    image: mariadb
    container_name: admin_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
