version: '3'

services:
  admin_web:
    build: ./e-commerce-PHP/WEB
    image: httpd:latest
    container_name: admin_web
    ports:
      - '8000:80'
    volumes:
      - ./website:/usr/local/apache2/htdocs


  admin_db:
    build: ./e-commerce-PHP/DB
    image: mariadb
    container_name: admin_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
